### Numpy Library 

In [2]:
# Recognise numpy library #

import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a * b)

[ 5 12 21 32]


In [3]:
# Numpy array: 'create array from list'

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a = np.array([1, 2.5, 3, 4])
print(a)

[1.  2.5 3.  4. ]


In [6]:
a = np.array([3.45, 7, 9, 11.25], dtype = "int")
print(a)

[ 3  7  9 11]


In [7]:
# create array from zero

np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype = 'int') # create ones array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,5), 'a')

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [11]:
np.arange(0,33,3) # start three by three from zero until thirty three

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.linspace(0,1,10) # between zero and one 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10,4,(3,4)) # avarage 10, standart deviation 4

array([[14.97694459, 12.19851452,  7.90290891, 13.2903765 ],
       [ 6.50740046, 11.92025184,  5.81557366,  8.28505815],
       [10.8350876 , 10.28220893,  7.94070231, 12.99842244]])

In [14]:
np.random.randint(0,10,(3,3)) # random numbers

array([[2, 9, 4],
       [0, 4, 6],
       [5, 7, 8]])

### Array Features

In [15]:
# ndim: give number of dimension
# shape: give info of dimension
# size: give total number of elements
# dtype: give array data type

In [16]:
a = np.random.randint(10,size=10)
print(a.ndim)

1


In [17]:
print(a.size)

10


In [18]:
print(a.dtype)

int32


### restatement (reshaping) 

In [20]:
a = np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Concatenation (array joining) 

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

j_array = np.concatenate([x,y,z])
print(j_array)

[1 2 3 4 5 6 7 8 9]


In [23]:
# two dimension joining

a = np.array([[1,2,3],
             [4,5,6]])
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
b = np.array([[5,6,7],
             [8,9,10]])
np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10]])